/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import helper.List_barang;
import helper.Tbl_barang;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import models.M_barang;

/**
 *
 * @author Klaus
 */
public class v_barangedit extends javax.swing.JDialog {
    M_barang model = new M_barang();
    List<List_barang> data = new ArrayList<>();
    Tbl_barang tbl_model = new Tbl_barang(data);
    private String kd_brg, nm_brg, kds_brg, stuan, hargabeli, hargajual;
    private int stok_brg;
    JTable tbl_barang;
    /**
     * Creates new form v_barangedit
     * @param kd_barang
     * @param nama
     * @param kondisi
     * @param satuan
     * @param stok
     * @param hargab
     * @param hargaj
     * @param tbl_brg
     */
    public v_barangedit(String kd_barang, String nama, String kondisi, String satuan, int stok, String hargab, String hargaj, JTable tbl_brg) {
        initComponents();
        this.t_kdbrg.setEnabled(false);
        kd_brg = kd_barang;
        nm_brg = nama;
        kds_brg = kondisi;
        stuan = satuan;
        stok_brg = stok;
        hargabeli = hargab;
        hargajual = hargaj;
        tbl_barang = tbl_brg;
        this.sck();
        this.setTable();   
    }
    
    private void setTable(){
        this.setLocationRelativeTo(null);
        t_kdbrg.setText(kd_brg);
        t_nmbrg.setText(nm_brg);
        t_satuan.setText(stuan);
        t_stok.setText(Integer.toString(stok_brg));
        t_hrg.setText(hargabeli);
    }
    
    private void proses(){
        model.setKodeBrg(String.valueOf(this.t_kdbrg.getText()));
        model.setNamaBrg(String.valueOf(this.t_nmbrg.getText()));
        model.setHarga(String.valueOf(this.t_hrg.getText()));
        model.setHargajual(String.valueOf(hargajual));
        model.setSatuanBrg(String.valueOf(this.t_satuan.getText()));
        model.setKondisiBrg(String.valueOf(kds_brg));
        model.setStokBrg(Integer.valueOf(this.t_stok.getText()));
    }
    
    private void sck(){
        if(kds_brg.equals("Baru")){
            ck_b.setSelected(true);
        }else{
            ck_bk.setSelected(false);
        }
    }
    
    private void loadtable(){
        data = model.Load1("");
        tbl_model = new Tbl_barang(data);
        tbl_barang.setModel(tbl_model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t_nmbrg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_kdbrg = new javax.swing.JTextField();
        ck_b = new javax.swing.JCheckBox();
        ck_bk = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        t_satuan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t_stok = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t_hrg = new javax.swing.JTextField();
        close = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kondisi Barang");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 160, 36));

        t_nmbrg.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel2.add(t_nmbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 270, 36));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Nama Barang");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 83, 36));

        t_kdbrg.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel2.add(t_kdbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 270, 36));

        ck_b.setBackground(new java.awt.Color(255, 255, 255));
        ck_b.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck_b.setText("Baru");
        ck_b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ck_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_bActionPerformed(evt);
            }
        });
        jPanel2.add(ck_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 90, 40));

        ck_bk.setBackground(new java.awt.Color(255, 255, 255));
        ck_bk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck_bk.setText("Bekas");
        ck_bk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ck_bk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_bkActionPerformed(evt);
            }
        });
        jPanel2.add(ck_bk, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 90, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Kode Barang");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 83, 36));

        btn_save.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_save.setText("Edit");
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });
        jPanel2.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 130, 40));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Satuan");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 83, 36));

        t_satuan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel2.add(t_satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 270, 36));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Stok");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 83, 36));

        t_stok.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel2.add(t_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 270, 36));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Harga");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 83, 36));

        t_hrg.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel2.add(t_hrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 270, 36));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 410, 470));

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/close_32px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 30, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Edit Data Barang");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 20));

        tgl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ck_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_bActionPerformed
        if(ck_b.isSelected()){
            this.kds_brg = "Baru";
            this.ck_bk.setSelected(false);
            int i = 100000;
            int a = Integer.parseInt(t_hrg.getText());
            int h = i + a;
            hargajual = Integer.toString(h);
        }
    }//GEN-LAST:event_ck_bActionPerformed

    private void ck_bkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_bkActionPerformed
        if(ck_bk.isSelected()){
            this.kds_brg = "Bekas";
            this.ck_b.setSelected(false);
            int i = 25000;
            int a = Integer.parseInt(t_hrg.getText());
            int h = i + a;
            hargajual = Integer.toString(h);
        }
    }//GEN-LAST:event_ck_bkActionPerformed

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked
        if(this.t_kdbrg.getText().equals("")
            || this.t_nmbrg.getText().equals("")
            || this.t_satuan.getText().equals("")
            || this.t_stok.getText().equals("")
            || this.t_hrg.getText().equals("")){
            model.msg.validasidata();
        }else{   
            this.proses();
            model.Updatesup();
            this.loadtable();
            this.dispose();
        }
    }//GEN-LAST:event_btn_saveMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("icon/exitred_32px.png"));
        close.setIcon(A);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("icon/close_32px.png"));
        close.setIcon(A);
    }//GEN-LAST:event_closeMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JCheckBox ck_b;
    private javax.swing.JCheckBox ck_bk;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField t_hrg;
    private javax.swing.JTextField t_kdbrg;
    private javax.swing.JTextField t_nmbrg;
    private javax.swing.JTextField t_satuan;
    private javax.swing.JTextField t_stok;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables
}
