/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import helper.List_barang;
import helper.Tbl_barang;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import models.M_barang;
/**
 *
 * @author Klaus
 */
public class v_barangbaru extends javax.swing.JDialog {
    M_barang model = new M_barang();
    List<List_barang> data = new ArrayList<>();
    Tbl_barang tbl_model = new Tbl_barang(data);
    String kondisi = "";
    JTable tbl_sup;
    String jual;
    /**
     * Creates new form v_dsupplier
     * @param tbl_bar
     */
    public v_barangbaru(JTable tbl_bar) {
        initComponents();
        this.OptionsFrame();
        this.tanggal();
        this.awal();
        tbl_sup = tbl_bar;
    }
    
    private void OptionsFrame(){
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
    }
    
    private void table(){
        data = model.Load1("");
        tbl_model = new Tbl_barang(data);
        tbl_sup.setModel(tbl_model);
    }
    private void awal(){
        this.t_nmbrg.setText("");
        this.kondisi = "";
        this.t_satuan.setText("");
        this.ck_b.setSelected(false);
        this.ck_bk.setSelected(false);
    }
    
    private void tanggal(){
        tgl.setText(model.tanggalnow);
    }
    
    private void proses(){
        int sb = 0;
        model.setKodeBrg(String.valueOf(model.Barangkode()));
        model.setNamaBrg(String.valueOf(this.t_nmbrg.getText()));
        model.setHarga(String.valueOf(this.t_harga.getText()));
        model.setHargajual(String.valueOf(jual));
        model.setSatuanBrg(String.valueOf(this.t_satuan.getText()));
        model.setKondisiBrg(String.valueOf(this.kondisi));
        model.setStokBrg(sb);
    }
     
    private void simpan(){
        if(this.t_nmbrg.getText().equals("")
            || this.t_satuan.getText().equals("")
            || this.t_harga.getText().equals("")
            || this.t_harga.getText().equals("0")    
            || this.ck_b.equals(false)
            || this.ck_bk.equals(false)){
                model.msg.validasidata();
        }else{   
            this.proses();
            model.Simpan();
            this.awal();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t_nmbrg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ck_b = new javax.swing.JCheckBox();
        ck_bk = new javax.swing.JCheckBox();
        btn_batal = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        t_satuan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t_harga = new javax.swing.JTextField();
        close = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kondisi Barang");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 160, 36));

        t_nmbrg.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel2.add(t_nmbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 270, 36));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Nama Barang");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 83, 36));

        ck_b.setBackground(new java.awt.Color(255, 255, 255));
        ck_b.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck_b.setText("Baru");
        ck_b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ck_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_bActionPerformed(evt);
            }
        });
        jPanel2.add(ck_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, 40));

        ck_bk.setBackground(new java.awt.Color(255, 255, 255));
        ck_bk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ck_bk.setText("Bekas");
        ck_bk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ck_bk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_bkActionPerformed(evt);
            }
        });
        jPanel2.add(ck_bk, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 90, 40));

        btn_batal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });
        jPanel2.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 80, 40));

        btn_save.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_save.setText("Simpan");
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });
        jPanel2.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 80, 40));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Satuan");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 83, 36));

        t_satuan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel2.add(t_satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 270, 36));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Harga");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 83, 36));

        t_harga.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel2.add(t_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 270, 36));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 410, 420));

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/close_32px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 30, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Input Data Barang");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 20));

        tgl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("icon/exitred_32px.png"));
        close.setIcon(A);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("icon/close_32px.png"));
        close.setIcon(A);
    }//GEN-LAST:event_closeMouseExited

    private void ck_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_bActionPerformed
        if(ck_b.isSelected()){
            this.kondisi = "Baru";
            int i = 100000;
            int a = Integer.parseInt(t_harga.getText());
            int h = i + a;
            jual = Integer.toString(h);
            this.ck_bk.setSelected(false);        
        }
    }//GEN-LAST:event_ck_bActionPerformed

    private void ck_bkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_bkActionPerformed
        if(ck_bk.isSelected()){
           this.kondisi = "Bekas";
           int i = 25000;
           int a = Integer.parseInt(t_harga.getText());
           int h = i + a;
           jual = Integer.toString(h);
           this.ck_b.setSelected(false);
        }
    }//GEN-LAST:event_ck_bkActionPerformed

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked
        this.simpan();
        this.table();
    }//GEN-LAST:event_btn_saveMouseClicked

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        this.awal();
    }//GEN-LAST:event_btn_batalMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_save;
    private javax.swing.JCheckBox ck_b;
    private javax.swing.JCheckBox ck_bk;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField t_harga;
    private javax.swing.JTextField t_nmbrg;
    private javax.swing.JTextField t_satuan;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables
}
