/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import helper.List_penjualan;
import helper.Message;
import helper.Tbl_penjualan;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import models.M_kasir;

/**
 *
 * @author Klaus
 */
public class v_datapenjualan extends javax.swing.JFrame {
    List<List_penjualan> data = new ArrayList<>();
    Tbl_penjualan tbl_model = new Tbl_penjualan(data);
    M_kasir model = new M_kasir();
    Message msg = new Message();
    private String id, pos, nm;
    /**
     * Creates new form v_datapenjualan
     * @param id_user
     * @param nama
     * @param posisi
     */
    public v_datapenjualan(String id_user, String nama, String posisi) {
        initComponents();
        this.Options();
        this.tanggal();
        model.koneksi();
        id = id_user;
        nm = nama;
        pos = posisi;
        this.setprofile();
        this.loadtable();
        this.awal();
        tid.setVisible(false);
    }
    
    private void awal(){
        jdc1.setDate(null);
        jdc2.setDate(null);
    }
    
    private void tanggal(){
        tgl.setText(model.tanggalnow);
    }
    
    private void loadtable(){
        data = model.Load1("");
        tbl_model = new Tbl_penjualan(data);
        tbl_persed.setModel(tbl_model);
    }
    
    private void setprofile(){
        tid.setText(id);
        nma.setText(nm);
        tpos.setText(pos);
    }
    
    private void profile(){
        id = tid.getText();
        nm = nma.getText();
        pos = tpos.getText();
    }
    
    private void Options(){
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
    }
    
    private void printimg(){
        ImageIcon A = new ImageIcon(getClass().getResource("icon/printred_32px.png"));
        print1.setIcon(A);
    }
    
    private void cetak(){
        if(jdc1.getDate()==null
                || jdc2.getDate()==null){
            msg.Tanggal();
        }else{
            model.Cetak(this.jdc1.getDate(), this.jdc2.getDate());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        profile = new javax.swing.JPanel();
        mn_profile = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nma = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        item = new javax.swing.JPanel();
        mn_lap2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        trans = new javax.swing.JPanel();
        mn_sells = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        mn_logout = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_persed = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tpos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        tid = new javax.swing.JLabel();
        tjam = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jdc1 = new com.toedter.calendar.JDateChooser();
        jdc2 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        print1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setBackground(new java.awt.Color(54, 33, 89));
        profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mn_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_profileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mn_profileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mn_profileMouseExited(evt);
            }
        });
        profile.add(mn_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/gender_neutral_user_32px.png"))); // NOI18N
        profile.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 40, 50));

        nma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nma.setForeground(new java.awt.Color(255, 255, 255));
        nma.setText("Klaus");
        profile.add(nma, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 0, 170, 50));

        sidepane.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 10));

        item.setBackground(new java.awt.Color(64, 43, 100));
        item.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mn_lap2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_lap2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mn_lap2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mn_lap2MouseExited(evt);
            }
        });
        item.add(mn_lap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/pdf_32px.png"))); // NOI18N
        item.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 42, 50));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Laporan Barang");
        item.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 0, 172, 50));

        sidepane.add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 50));

        jPanel2.setBackground(new java.awt.Color(85, 55, 118));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/banknotes_32px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 42, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Penjualan Barang");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 0, 172, 50));

        sidepane.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, 50));

        trans.setBackground(new java.awt.Color(64, 43, 100));
        trans.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mn_sells.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_sellsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mn_sellsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mn_sellsMouseExited(evt);
            }
        });
        trans.add(mn_sells, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/shopping_cart_32px.png"))); // NOI18N
        trans.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 42, 50));

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Penjualan Barang");
        trans.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 11, 172, 39));

        sidepane.add(trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 50));

        logout.setBackground(new java.awt.Color(64, 43, 100));
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mn_logoutMouseExited(evt);
            }
        });
        logout.add(mn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/exit_32px.png"))); // NOI18N
        logout.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 42, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Logout");
        logout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 11, 172, 39));

        sidepane.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, -1, -1));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 660));

        tbl_persed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_persed);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 700, 340));

        jPanel1.setBackground(new java.awt.Color(122, 72, 221));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Menu Barang Keluar");

        tpos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tpos.setForeground(new java.awt.Color(255, 255, 255));
        tpos.setText("Admin");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/img/LOGO.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tpos, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(tpos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 700, 150));

        btn_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/close_window_32px.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_closeMouseExited(evt);
            }
        });
        bg.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 30, 30));

        tgl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tgl.setText("tgl");
        bg.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 150, 30));
        bg.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 110, 20));
        bg.add(tjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 130, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jdc1.setDateFormatString("dd/MM/yyyy");

        jdc2.setDateFormatString("dd/MM/yyyy");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Cetak Dari Periode");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Dari Tanggal");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Sampai");

        print1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/print_32px.png"))); // NOI18N
        print1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                print1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                print1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                print1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                print1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdc2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdc1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(print1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jdc1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdc2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(print1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))))
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 360, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_profileMouseClicked
        this.profile();
        this.model.KeGantiPass(tid);
    }//GEN-LAST:event_mn_profileMouseClicked

    private void mn_profileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_profileMouseEntered
        this.profile.setBackground(new Color(85,55,118));
    }//GEN-LAST:event_mn_profileMouseEntered

    private void mn_profileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_profileMouseExited
        this.profile.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_mn_profileMouseExited

    private void mn_lap2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_lap2MouseClicked
        model.laporan11();
    }//GEN-LAST:event_mn_lap2MouseClicked

    private void mn_lap2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_lap2MouseEntered
        this.item.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_mn_lap2MouseEntered

    private void mn_lap2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_lap2MouseExited
        this.item.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_mn_lap2MouseExited

    private void mn_sellsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_sellsMouseClicked
        this.profile();
        model.KKasir(id, nm, pos);
        this.dispose();
    }//GEN-LAST:event_mn_sellsMouseClicked

    private void mn_sellsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_sellsMouseEntered
        this.trans.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_mn_sellsMouseEntered

    private void mn_sellsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_sellsMouseExited
        this.trans.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_mn_sellsMouseExited

    private void mn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_logoutMouseClicked
        model.Logout();
        this.dispose();
    }//GEN-LAST:event_mn_logoutMouseClicked

    private void mn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_logoutMouseEntered
        this.logout.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_mn_logoutMouseEntered

    private void mn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_logoutMouseExited
        this.logout.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_mn_logoutMouseExited

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        msg.keluar();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("icon/exitred_32px.png"));
        btn_close.setIcon(A);
    }//GEN-LAST:event_btn_closeMouseEntered

    private void btn_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("icon/close_window_32px.png"));
        btn_close.setIcon(A);
    }//GEN-LAST:event_btn_closeMouseExited

    private void print1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print1MouseClicked
        this.cetak();
    }//GEN-LAST:event_print1MouseClicked

    private void print1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print1MouseEntered
        printimg();
    }//GEN-LAST:event_print1MouseEntered

    private void print1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print1MouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("icon/print_32px.png"));
        print1.setIcon(A);
    }//GEN-LAST:event_print1MouseExited

    private void print1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print1MousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("icon/print_green32px.png"));
        print1.setIcon(A);
    }//GEN-LAST:event_print1MousePressed

    private void print1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print1MouseReleased
        printimg();
    }//GEN-LAST:event_print1MouseReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btn_close;
    private javax.swing.JPanel item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jdc1;
    private com.toedter.calendar.JDateChooser jdc2;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel mn_lap2;
    private javax.swing.JLabel mn_logout;
    private javax.swing.JLabel mn_profile;
    private javax.swing.JLabel mn_sells;
    private javax.swing.JLabel nma;
    private javax.swing.JLabel print1;
    private javax.swing.JPanel profile;
    private javax.swing.JPanel sidepane;
    private javax.swing.JTable tbl_persed;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel tid;
    private javax.swing.JLabel tjam;
    private javax.swing.JLabel tpos;
    private javax.swing.JPanel trans;
    // End of variables declaration//GEN-END:variables
}
