/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import models.M_user;
/**
 *
 * @author Klaus
 */
public class v_gantipass extends javax.swing.JDialog {
    String ids, nms, poss, emails, tgls, pendis;
    M_user model = new M_user();
    /**
     * Creates new form v_gantipass
     * @param id
     * @param nama
     * @param pos
     * @param email
     * @param tanggall
     * @param pendi
     */
    public v_gantipass(String id , String nama, String pos, String email, String tanggall, String pendi){
        initComponents();
        this.OptionsFrame();
        this.awal();
        ids = id;
        nms = nama;
        poss = pos;
        emails = email;
        tgls = tanggall;
        pendis = pendi;
        setProfile();
    }
    
    private void setProfile(){
        t_id.setText(ids);
        t_nama.setText(nms);
        t_jabat.setText(poss);
        temail.setText(emails);
        t_tanggal.setText(tgls);
        tpendidikan.setText(pendis);
    }
    
    private void OptionsFrame(){
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
        this.tsamaulang.setVisible(false);
    }
    
    private void awal(){
        this.tpasslama.setText("");
        this.tketikulang.setText("");
        this.tpassbaru.setText("");
        this.tpasslama.requestFocus();
        this.tpassbaru.setEnabled(false);
        this.tketikulang.setEnabled(false);
    }
    
    private void password(){
        String password = this.tpassbaru.getText();
        if(this.tketikulang.getText().equals(tpassbaru.getText())){
            this.tsamaulang.setVisible(false);
        }else{
            this.tsamaulang.setVisible(true);
        }
    }
    
    private void passLama(){
        model.Confirmpass(this.tpasslama, this.tpassbaru, this.tketikulang, this.t_id);
    }
    
    private void ok(){
        if(tketikulang.getText().equals(tpassbaru.getText())){
            model.okuser(this.tketikulang, this.t_id);
            this.awal();
        }else{
            model.msg.passmatch();
            this.awal();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tketikulang = new javax.swing.JPasswordField();
        tpassbaru = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        t_id = new javax.swing.JLabel();
        t_nama = new javax.swing.JLabel();
        t_jabat = new javax.swing.JLabel();
        t_tanggal = new javax.swing.JLabel();
        tpendidikan = new javax.swing.JLabel();
        temail = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tsamaulang = new javax.swing.JLabel();
        show2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tpasslama = new javax.swing.JPasswordField();
        t_jabat1 = new javax.swing.JLabel();
        t_jabat2 = new javax.swing.JLabel();
        t_jabat3 = new javax.swing.JLabel();
        t_jabat4 = new javax.swing.JLabel();
        t_jabat5 = new javax.swing.JLabel();
        t_jabat6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        close = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tketikulang.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tketikulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tketikulangActionPerformed(evt);
            }
        });
        tketikulang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tketikulangKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tketikulangKeyTyped(evt);
            }
        });
        jPanel2.add(tketikulang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 200, 40));

        tpassbaru.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel2.add(tpassbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 200, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Ketik Ulang Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 150, 40));

        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/visible_32px.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel2.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 40, 40));

        t_id.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        t_id.setText("Id Anggota");
        jPanel2.add(t_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 240, 40));

        t_nama.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        t_nama.setText("Nama");
        jPanel2.add(t_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 240, 40));

        t_jabat.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        t_jabat.setText("Jabatan");
        jPanel2.add(t_jabat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 240, 40));

        t_tanggal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        t_tanggal.setText("Tanggal Lahir");
        jPanel2.add(t_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 210, 40));

        tpendidikan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tpendidikan.setText("Pendidikan Terakhir");
        jPanel2.add(tpendidikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 200, 40));

        temail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        temail.setText("Email");
        jPanel2.add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 180, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Password Baru");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 150, 40));

        tsamaulang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tsamaulang.setForeground(new java.awt.Color(255, 0, 0));
        tsamaulang.setText("Password Baru Tidak Sama");
        jPanel2.add(tsamaulang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 250, 30));

        show2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/visiblegreen_32px.png"))); // NOI18N
        show2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show2MouseClicked(evt);
            }
        });
        jPanel2.add(show2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 40, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Password Lama");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 150, 40));

        tpasslama.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tpasslama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tpasslamaKeyPressed(evt);
            }
        });
        jPanel2.add(tpasslama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 200, 40));

        t_jabat1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        t_jabat1.setText("Tanggal Lahir     :");
        jPanel2.add(t_jabat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 40));

        t_jabat2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        t_jabat2.setText("Email                   :");
        jPanel2.add(t_jabat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 40));

        t_jabat3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        t_jabat3.setText("ID                          :");
        jPanel2.add(t_jabat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 40));

        t_jabat4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        t_jabat4.setText("Nama                   :");
        jPanel2.add(t_jabat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 40));

        t_jabat5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        t_jabat5.setText("Jabatan               :");
        jPanel2.add(t_jabat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 40));

        t_jabat6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        t_jabat6.setText("Pendidkan          :");
        jPanel2.add(t_jabat6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 40));

        jButton1.setText("Batal");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 70, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 420, 580));

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/close_32px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ganti Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 20));

        tgl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tketikulangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tketikulangKeyPressed
        this.password();
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(tpassbaru.getText().equals("")
                        ||tketikulang.getText().equals("")){
                    model.msg.validasidata();
            }else{
                this.ok();
            }
        }    
    }//GEN-LAST:event_tketikulangKeyPressed

    private void tketikulangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tketikulangKeyTyped
        this.password();
    }//GEN-LAST:event_tketikulangKeyTyped

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        this.tpassbaru.setEchoChar((char)0);
        this.tpasslama.setEchoChar((char)0);
        this.tketikulang.setEchoChar((char)0);
        this.show.setVisible(false);
        this.show2.setVisible(true);
    }//GEN-LAST:event_showMouseClicked

    private void show2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show2MouseClicked
        this.tpassbaru.setEchoChar('*');
        this.tpasslama.setEchoChar('*');
        this.tketikulang.setEchoChar('*');
        this.show.setVisible(true);
        this.show2.setVisible(false);
    }//GEN-LAST:event_show2MouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("icon/exitred_32px.png"));
        close.setIcon(A);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("icon/close_32px.png"));
        close.setIcon(A);
    }//GEN-LAST:event_closeMouseExited

    private void tpasslamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpasslamaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(tpasslama.getText().equals("")){
                model.msg.validasidata();
            }else{
                this.passLama();
            }
        }
    }//GEN-LAST:event_tpasslamaKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.awal();
    }//GEN-LAST:event_jButton1MouseClicked

    private void tketikulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tketikulangActionPerformed
        this.password();
    }//GEN-LAST:event_tketikulangActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel show;
    private javax.swing.JLabel show2;
    private javax.swing.JLabel t_id;
    private javax.swing.JLabel t_jabat;
    private javax.swing.JLabel t_jabat1;
    private javax.swing.JLabel t_jabat2;
    private javax.swing.JLabel t_jabat3;
    private javax.swing.JLabel t_jabat4;
    private javax.swing.JLabel t_jabat5;
    private javax.swing.JLabel t_jabat6;
    private javax.swing.JLabel t_nama;
    private javax.swing.JLabel t_tanggal;
    private javax.swing.JLabel temail;
    private javax.swing.JLabel tgl;
    private javax.swing.JPasswordField tketikulang;
    private javax.swing.JPasswordField tpassbaru;
    private javax.swing.JPasswordField tpasslama;
    private javax.swing.JLabel tpendidikan;
    private javax.swing.JLabel tsamaulang;
    // End of variables declaration//GEN-END:variables
}
