/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import config.session;
import helper.Message;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
/**
 *
 * @author Klaus
 */
public class v_login extends javax.swing.JFrame {
    Message mail = new Message();
    int dragxmouse;
    int dragymouse;
    /**
     * Creates new form v_login
     */
    public v_login() {
        initComponents();
        this.OptionsFrame();
    }
    
    private void OptionsFrame(){
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
        btn_signin.requestFocus();
    }
    
    private void Icon1(){
        ImageIcon A = new ImageIcon(getClass().getResource("background/btn_x1.png"));
        icon_x.setIcon(A);
    }
    
    private void Icon2(){
        ImageIcon A = new ImageIcon(getClass().getResource("background/btn_x2.png"));
        icon_x.setIcon(A);
    }
    
    private void Icon3(){
        ImageIcon A = new ImageIcon(getClass().getResource("background/btn_x3.png"));
        icon_x.setIcon(A);
    }
    
    private void login(){
        session log = new session();
        log.login = this;
        log.setEmail(String.valueOf(this.t_id.getText()));
        log.setPass(String.valueOf(this.t_pass.getText()));
        if(this.t_id.getText().equals("")&&this.t_pass.getText().equals("")){
                mail.validasi();
        }else if(this.t_id.getText().equals("")){
            mail.valus();
        }else if(this.t_pass.getText().equals("")){
            mail.valpass();
        }else{
            log.simpleSession();
        }    
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon_x = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        t_pass = new javax.swing.JPasswordField();
        btn_signin = new javax.swing.JLabel();
        frame_drag = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(680, 566));
        setSize(new java.awt.Dimension(680, 566));
        getContentPane().setLayout(null);

        icon_x.setBackground(new java.awt.Color(102, 0, 204));
        icon_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/background/btn_x1.png"))); // NOI18N
        icon_x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon_xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon_xMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon_xMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                icon_xMouseReleased(evt);
            }
        });
        getContentPane().add(icon_x);
        icon_x.setBounds(590, 20, 50, 50);

        t_id.setBackground(new java.awt.Color(54, 33, 89));
        t_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        t_id.setForeground(new java.awt.Color(255, 255, 255));
        t_id.setBorder(null);
        t_id.setCaretColor(new java.awt.Color(255, 255, 255));
        t_id.setOpaque(false);
        getContentPane().add(t_id);
        t_id.setBounds(150, 170, 380, 70);

        t_pass.setBackground(new java.awt.Color(54, 33, 89));
        t_pass.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        t_pass.setForeground(new java.awt.Color(255, 255, 255));
        t_pass.setBorder(null);
        t_pass.setCaretColor(new java.awt.Color(255, 255, 255));
        t_pass.setOpaque(false);
        t_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_passKeyPressed(evt);
            }
        });
        getContentPane().add(t_pass);
        t_pass.setBounds(150, 280, 380, 70);

        btn_signin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/background/btn_logIn1.png"))); // NOI18N
        btn_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_signinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_signinMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_signinMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_signinMouseReleased(evt);
            }
        });
        getContentPane().add(btn_signin);
        btn_signin.setBounds(130, 380, 410, 90);

        frame_drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frame_dragMouseDragged(evt);
            }
        });
        frame_drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frame_dragMousePressed(evt);
            }
        });
        getContentPane().add(frame_drag);
        frame_drag.setBounds(-10, 0, 660, 550);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/background/bg_full.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 670, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icon_xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_xMouseClicked
        mail.keluar();
    }//GEN-LAST:event_icon_xMouseClicked

    private void icon_xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_xMouseEntered
        this.Icon2();
    }//GEN-LAST:event_icon_xMouseEntered

    private void icon_xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_xMouseExited
        this.Icon1();
    }//GEN-LAST:event_icon_xMouseExited

    private void icon_xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_xMousePressed
        this.Icon3();
    }//GEN-LAST:event_icon_xMousePressed

    private void icon_xMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_xMouseReleased
        this.Icon2();
    }//GEN-LAST:event_icon_xMouseReleased

    private void frame_dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frame_dragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - dragxmouse, y - dragymouse);
        System.out.println(x+","+y);
    }//GEN-LAST:event_frame_dragMouseDragged

    private void frame_dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frame_dragMousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_frame_dragMousePressed

    private void btn_signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signinMouseClicked
        this.login();
    }//GEN-LAST:event_btn_signinMouseClicked

    private void btn_signinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signinMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("background/btn_logIn2.png"));
        btn_signin.setIcon(A);
    }//GEN-LAST:event_btn_signinMouseEntered

    private void btn_signinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signinMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("background/btn_logIn1.png"));
        btn_signin.setIcon(A);
    }//GEN-LAST:event_btn_signinMouseExited

    private void btn_signinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signinMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("background/btn_logIn3.png"));
        btn_signin.setIcon(A);
    }//GEN-LAST:event_btn_signinMousePressed

    private void btn_signinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signinMouseReleased
        ImageIcon A = new ImageIcon(getClass().getResource("background/btn_logIn2.png"));
        btn_signin.setIcon(A);
    }//GEN-LAST:event_btn_signinMouseReleased

    private void t_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_passKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.login();
        }
    }//GEN-LAST:event_t_passKeyPressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btn_signin;
    private javax.swing.JLabel frame_drag;
    private javax.swing.JLabel icon_x;
    private javax.swing.JTextField t_id;
    private javax.swing.JPasswordField t_pass;
    // End of variables declaration//GEN-END:variables
}
