/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import controllers.Barang;
import models.M_barang;
import helper.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import models.M_suppliers;
/**
 *
 * @author Klaus
 */
public class v_pilihbarang1 extends javax.swing.JDialog {
    M_barang brg = new M_barang();
    M_suppliers model = new M_suppliers();
    List<List_barang> data = new ArrayList<>();   
    Tbl_barang tbl_model = new Tbl_barang(data);
    JTable tb_sup;
    JLabel gsubtotal, gstoktotal;
    String harga = "";
    String hargajual = "";
    /**
     * Creates new form v_tablebarang
     * @param tbl_sup
     * @param total
     * @param stoktotal
     */
    public v_pilihbarang1(JTable tbl_sup, JLabel total, JLabel stoktotal){
        initComponents();
        this.table();
        this.tanggal();
        this.OptionsFrame();
        this.awal();
        tb_sup = tbl_sup;  
        gsubtotal = total;
        gstoktotal = stoktotal; 
    }
    
    private void OptionsFrame(){
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
        this.t_kd.setVisible(false);
        this.t_nm.setVisible(false);
        this.t_kon.setVisible(false);
        this.t_sat.setVisible(false);
        this.t_stok.setVisible(false);
        this.tjum.setVisible(false);
        this.total.setVisible(false);
    }
    
    private void awal(){
        this.lbl35.setEnabled(false);
        this.stok.setEnabled(false);
        this.jButton1.setEnabled(false);
        this.stok.setText("");
    }
    
    private void Klick(){
        model.barubarang(this.tbl_barang2);
    }
    
    private void tanggal(){
        tgl.setText(brg.tanggalnow);
    }
    
    private void table(){
        data = brg.Load1("");
        tbl_model = new Tbl_barang(data);
        tbl_barang2.setModel(tbl_model);
    }
    
    private void cari(){
        brg.Cari(cari, tbl_barang2);
    }
    
    private void settable(){
        int i = tbl_barang2.getSelectedRow();
        String kd_brg = tbl_barang2.getValueAt(i, 0).toString();
        Barang d = brg.pilihdata1(kd_brg);
        t_kd.setText(d.getKodeBrg());
        t_nm.setText(d.getNamaBrg());
        t_stok.setText(Integer.toString(d.getStokBrg()));
        t_sat.setText(d.getSatuanBrg());
        t_kon.setText(d.getKondisiBrg());
        harga = d.getHarga();
        hargajual = d.getHargajual();
        this.jButton1.setEnabled(true);
    }
    
    private void proses(){
        model.setKodeBrg(String.valueOf(this.t_kd.getText()));
        model.setNamaBrg(String.valueOf(this.t_nm.getText()));
        model.setHargabeli(String.valueOf(harga));
        model.setSatuanBrg(String.valueOf(this.t_sat.getText()));
        model.setKondisiBrg(String.valueOf(this.t_kon.getText()));
        model.setStokBrg(String.valueOf(this.stok.getText()));
        model.setTotal(String.valueOf(this.total.getText()));
        brg.setKodeBrg(String.valueOf(this.t_kd.getText()));
        brg.setNamaBrg(String.valueOf(this.t_nm.getText()));
        brg.setSatuanBrg(String.valueOf(this.t_sat.getText()));
        brg.setKondisiBrg(String.valueOf(this.t_kon.getText()));
        brg.setStokBrg(Integer.valueOf(this.tjum.getText()));
        brg.setHarga(harga);
        brg.setHargajual(hargajual);
    }
    
    private void Tableconfig(){
        this.proses();
        model.tablerow(this.tb_sup);
        model.hitung(tb_sup, gstoktotal, gsubtotal);
    }
    
    private void hitung(){
        int y = Integer.parseInt(t_stok.getText());
        int x = Integer.parseInt(stok.getText());
        double t = Double.parseDouble(harga);
        int baru = x + y;
        double subtotal = t * x;
        tjum.setText(Integer.toString(baru));
        total.setText(Double.toString(subtotal));
    }
    
    private void update(){
        this.proses();
        brg.Updatesup();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_barang2 = new javax.swing.JTable();
        stok = new javax.swing.JTextField();
        lbl35 = new javax.swing.JLabel();
        btn_new = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        t_kd = new javax.swing.JTextField();
        t_nm = new javax.swing.JTextField();
        t_sat = new javax.swing.JTextField();
        t_stok = new javax.swing.JTextField();
        t_kon = new javax.swing.JTextField();
        tjum = new javax.swing.JTextField();
        lbl4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        close = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_barang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_barang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barang2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_barang2);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 590, 270));

        stok.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        stok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stokKeyPressed(evt);
            }
        });
        jPanel2.add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 170, 30));

        lbl35.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl35.setText("Tekan Enter");
        jPanel2.add(lbl35, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 80, 30));

        btn_new.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/plus_32px.png"))); // NOI18N
        btn_new.setText("Tambah Barang Baru");
        btn_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_newMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_newMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_newMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_newMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_newMouseReleased(evt);
            }
        });
        jPanel2.add(btn_new, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        cari.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cariKeyTyped(evt);
            }
        });
        jPanel2.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 250, 30));

        lbl1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl1.setText("Cari Nama Barang");
        jPanel2.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 120, 30));
        jPanel2.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, 30));
        jPanel2.add(t_kd, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 40, 30));
        jPanel2.add(t_nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 80, 30));
        jPanel2.add(t_sat, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 60, 30));
        jPanel2.add(t_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 40, -1));
        jPanel2.add(t_kon, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 50, -1));
        jPanel2.add(tjum, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 40, -1));

        lbl4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl4.setText("Jumlah Beli");
        jPanel2.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 80, 30));

        jButton1.setText("Batal");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 590, 470));

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/close_32px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 30, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pilih Barang");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 20));

        tgl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("icon/exitred_32px.png"));
        close.setIcon(A);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("icon/close_32px.png"));
        close.setIcon(A);
    }//GEN-LAST:event_closeMouseExited

    private void tbl_barang2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barang2MouseClicked
        this.settable();
        this.stok.setEnabled(true);
        this.stok.requestFocus();
        this.jButton1.setEnabled(true);
    }//GEN-LAST:event_tbl_barang2MouseClicked

    private void cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyTyped
        this.cari();
    }//GEN-LAST:event_cariKeyTyped

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.awal();
    }//GEN-LAST:event_jButton1MouseClicked

    private void btn_newMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("icon/plus_green32px.png"));
        btn_new.setIcon(A);
    }//GEN-LAST:event_btn_newMousePressed

    private void btn_newMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("icon/plus_32px.png"));
        btn_new.setIcon(A);
    }//GEN-LAST:event_btn_newMouseExited

    private void btn_newMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("icon/plusred_32px.png"));
        btn_new.setIcon(A);
    }//GEN-LAST:event_btn_newMouseEntered

    private void btn_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newMouseClicked
        this.Klick();
    }//GEN-LAST:event_btn_newMouseClicked

    private void btn_newMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newMouseReleased
        ImageIcon A = new ImageIcon(getClass().getResource("icon/plusred_32px.png"));
        btn_new.setIcon(A);
    }//GEN-LAST:event_btn_newMouseReleased

    private void stokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stokKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(stok.getText().equals("")
                    || harga.equals("")
                    || stok.getText().equals("0")
                    || harga.equals("0")){
                brg.msg.JUMBEL();
            }else{
                this.hitung();
                this.Tableconfig();
                this.update();
                this.table();
                this.awal();
            }
        }
    }//GEN-LAST:event_stokKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_new;
    private javax.swing.JTextField cari;
    private javax.swing.JLabel close;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl35;
    private javax.swing.JLabel lbl4;
    private javax.swing.JTextField stok;
    private javax.swing.JTextField t_kd;
    private javax.swing.JTextField t_kon;
    private javax.swing.JTextField t_nm;
    private javax.swing.JTextField t_sat;
    private javax.swing.JTextField t_stok;
    private javax.swing.JTable tbl_barang2;
    private javax.swing.JLabel tgl;
    private javax.swing.JTextField tjum;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
