/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import models.M_suppliers;
import helper.*;
import java.awt.Color;
import javax.swing.ImageIcon;
/**
 *
 * @author Klaus
 */
public class v_supplier extends javax.swing.JFrame {
    M_suppliers model = new M_suppliers();
    Message msg = new Message();
    private String id, pos, nm;
    
    /**
     * Creates new form v_supplier
     * @param id_user
     * @param nama
     * @param posisi
     */
    public v_supplier(String id_user, String nama, String posisi){
        initComponents();
        this.OptionsFrame();
        this.tanggal();
        this.jam();
        this.awal();
        model.koneksi();
        id = id_user;
        nm = nama;
        pos = posisi;
        this.setprofile();
    }
    
    private void OptionsFrame(){
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
        this.tno.setEnabled(false);
        this.tid.setVisible(false);
        this.tjam.setVisible(false);
        jdc.setDate(model.tgls);
        jdc.setVisible(false);
    }
    
    private void tanggal(){
        tgl.setText(model.tanggalnow);
    }
    
    private void setprofile(){
        tid.setText(id);
        nma.setText(nm);
        tpos.setText(pos);
    }
    
    private void profile(){
        id = tid.getText();
        nm = nma.getText();
        pos = tpos.getText();
    }
    
    private void awal(){
        this.tno.setText("");
        this.btn_tambah.setEnabled(false);
        this.btn_c.setEnabled(true);
        this.btn_cetak.setEnabled(false);
        this.jButton1.setEnabled(false);
    }
    
    private void iplusb(){
        ImageIcon A = new ImageIcon(getClass().getResource("icon/plusred_32px.png"));
        btn_tambah.setIcon(A);
    }
    
    private void printimg(){
        ImageIcon A = new ImageIcon(getClass().getResource("icon/printred_32px.png"));
        btn_cetak.setIcon(A);
    }
    
    private void tambah(){
        model.tambahke(this.tbl_supp, this.subtotal, this.stoktotal);
    }
    
    private void hapustable(){
        model.hapusrow(this.tbl_supp);
        this.stoktotal.setText("0");
        this.subtotal.setText("0");
    }
    
    private void proses(){
        int ss = Integer.parseInt(stoktotal.getText());
        model.setNopersed(String.valueOf(this.tno.getText()));
        model.setStoktotal(ss);
        model.setSubtotal(String.valueOf(subtotal.getText()));
        model.setTanggal(this.jdc.getDate());
        model.setId(String.valueOf(this.tid.getText()));
    }
    
    private void jam(){
        model.setJam(this.tjam);
    }
    
    private void cetakno(){
        String x = "NP" + "-" + this.tgl.getText() + this.tjam.getText();
        this.tno.setText(x);
        this.btn_tambah.setEnabled(true);
        this.btn_cetak.setEnabled(true);
        this.btn_c.setEnabled(false);
        this.jButton1.setEnabled(true);
    }
  
    private void Simpan(){
        this.proses();
        this.model.Simpan(this.tbl_supp);
        this.model.Simpandet();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        mn_profile = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nma = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        item = new javax.swing.JPanel();
        mn_lap2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        mn_logout = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pers = new javax.swing.JPanel();
        mn_persediaan = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tpos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_supp = new javax.swing.JTable();
        btn_close = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        stoktotal = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JLabel();
        btn_c = new javax.swing.JButton();
        tno = new javax.swing.JTextField();
        subtotal = new javax.swing.JLabel();
        tid = new javax.swing.JLabel();
        tjam = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jdc = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supplier");
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(85, 55, 118));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/truck_32px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 42, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Persediaan Barang");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 0, 172, 50));

        sidepane.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 230, 50));

        profile.setBackground(new java.awt.Color(54, 33, 89));
        profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mn_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_profileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mn_profileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mn_profileMouseExited(evt);
            }
        });
        profile.add(mn_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/gender_neutral_user_32px.png"))); // NOI18N
        profile.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 40, 50));

        nma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nma.setForeground(new java.awt.Color(255, 255, 255));
        nma.setText("Klaus");
        profile.add(nma, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 0, 170, 50));

        sidepane.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 10));

        item.setBackground(new java.awt.Color(64, 43, 100));
        item.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mn_lap2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_lap2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mn_lap2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mn_lap2MouseExited(evt);
            }
        });
        item.add(mn_lap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/pdf_32px.png"))); // NOI18N
        item.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 42, 50));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Laporan Barang");
        item.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 0, 172, 50));

        sidepane.add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, 50));

        logout.setBackground(new java.awt.Color(64, 43, 100));
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mn_logoutMouseExited(evt);
            }
        });
        logout.add(mn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/exit_32px.png"))); // NOI18N
        logout.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 42, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Logout");
        logout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 11, 172, 39));

        sidepane.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, -1, -1));

        pers.setBackground(new java.awt.Color(64, 43, 100));
        pers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mn_persediaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_persediaanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mn_persediaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mn_persediaanMouseExited(evt);
            }
        });
        pers.add(mn_persediaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/box_32px.png"))); // NOI18N
        pers.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 42, 50));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Data Persediaan Barang");
        pers.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 11, 172, 39));

        sidepane.add(pers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 660));

        jPanel1.setBackground(new java.awt.Color(122, 72, 221));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Persediaan Barang");

        tpos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tpos.setForeground(new java.awt.Color(255, 255, 255));
        tpos.setText("Admin");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/img/LOGO.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tpos, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(tpos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 700, 150));

        tbl_supp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbl_supp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Satuan", "Kondisi", "Jumlah Beli", "Harga Pembelian", "Subtotal"
            }
        ));
        tbl_supp.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_supp.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tbl_supp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_suppMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_supp);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 700, 270));

        btn_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/close_window_32px.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_closeMouseExited(evt);
            }
        });
        bg.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 30, 30));

        tgl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tgl.setText("tgl");
        bg.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 150, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Total :");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, 90, 50));

        stoktotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        stoktotal.setText("0");
        bg.add(stoktotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 90, 50));

        btn_cetak.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_cetak.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/print_32px.png"))); // NOI18N
        btn_cetak.setText("SIMPAN");
        btn_cetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cetakMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cetakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cetakMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_cetakMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_cetakMouseReleased(evt);
            }
        });
        bg.add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 610, 100, 40));

        btn_tambah.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_tambah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icon/plus_32px.png"))); // NOI18N
        btn_tambah.setText("Tambah Barang");
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tambahMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_tambahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_tambahMouseReleased(evt);
            }
        });
        bg.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 140, 30));

        btn_c.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_c.setText("Cetak No Faktur");
        btn_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cMouseClicked(evt);
            }
        });
        bg.add(btn_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 140, 30));

        tno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bg.add(tno, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 190, 30));

        subtotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        subtotal.setText("0");
        bg.add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 560, 120, 50));
        bg.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 110, 20));
        bg.add(tjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 130, 30));

        jButton1.setText("Batal");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, -1, -1));
        bg.add(jdc, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_profileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_profileMouseEntered
        this.profile.setBackground(new Color(85,55,118));
    }//GEN-LAST:event_mn_profileMouseEntered

    private void mn_profileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_profileMouseExited
        this.profile.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_mn_profileMouseExited

    private void mn_lap2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_lap2MouseEntered
        this.item.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_mn_lap2MouseEntered

    private void mn_lap2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_lap2MouseExited
        this.item.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_mn_lap2MouseExited

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        msg.keluar();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("icon/exitred_32px.png"));
        btn_close.setIcon(A);
    }//GEN-LAST:event_btn_closeMouseEntered

    private void btn_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("icon/close_window_32px.png"));
        btn_close.setIcon(A);
    }//GEN-LAST:event_btn_closeMouseExited

    private void mn_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_profileMouseClicked
        this.profile();
        this.model.KeGantiPass(tid);
    }//GEN-LAST:event_mn_profileMouseClicked
        
    private void btn_cetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseClicked
        this.Simpan();      
        this.awal();
        this.hapustable();
    }//GEN-LAST:event_btn_cetakMouseClicked

    private void btn_cetakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseEntered
        this.printimg();
    }//GEN-LAST:event_btn_cetakMouseEntered

    private void btn_cetakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("icon/print_32px.png"));
        btn_cetak.setIcon(A);
    }//GEN-LAST:event_btn_cetakMouseExited

    private void btn_cetakMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("icon/print_green32px.png"));
        btn_cetak.setIcon(A);
    }//GEN-LAST:event_btn_cetakMousePressed

    private void btn_cetakMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseReleased
        this.printimg();
    }//GEN-LAST:event_btn_cetakMouseReleased

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        this.tambah();
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_tambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseEntered
        this.iplusb();
    }//GEN-LAST:event_btn_tambahMouseEntered

    private void btn_tambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("icon/plus_32px.png"));
        btn_tambah.setIcon(A);
    }//GEN-LAST:event_btn_tambahMouseExited

    private void btn_tambahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("icon/plus_green32px.png"));
        btn_tambah.setIcon(A);
    }//GEN-LAST:event_btn_tambahMousePressed

    private void btn_tambahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseReleased
        this.iplusb();
    }//GEN-LAST:event_btn_tambahMouseReleased

    private void tbl_suppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_suppMouseClicked
        model.msg.Hapustable(this.tbl_supp);
    }//GEN-LAST:event_tbl_suppMouseClicked

    private void btn_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cMouseClicked
        this.cetakno();
    }//GEN-LAST:event_btn_cMouseClicked

    private void mn_lap2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_lap2MouseClicked
        model.laporan11();
    }//GEN-LAST:event_mn_lap2MouseClicked

    private void mn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_logoutMouseClicked
        model.Logout();
        this.dispose();
    }//GEN-LAST:event_mn_logoutMouseClicked

    private void mn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_logoutMouseEntered
        this.logout.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_mn_logoutMouseEntered

    private void mn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_logoutMouseExited
        this.logout.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_mn_logoutMouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.awal();
        this.hapustable();
    }//GEN-LAST:event_jButton1MouseClicked

    private void mn_persediaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_persediaanMouseClicked
        this.profile();
        model.KePersediaan(id, nm, pos);
        this.dispose();
    }//GEN-LAST:event_mn_persediaanMouseClicked

    private void mn_persediaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_persediaanMouseEntered
        this.pers.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_mn_persediaanMouseEntered

    private void mn_persediaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_persediaanMouseExited
        this.pers.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_mn_persediaanMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_c;
    private javax.swing.JLabel btn_cetak;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_tambah;
    private javax.swing.JPanel item;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jdc;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel mn_lap2;
    private javax.swing.JLabel mn_logout;
    private javax.swing.JLabel mn_persediaan;
    private javax.swing.JLabel mn_profile;
    private javax.swing.JLabel nma;
    private javax.swing.JPanel pers;
    private javax.swing.JPanel profile;
    private javax.swing.JPanel sidepane;
    private javax.swing.JLabel stoktotal;
    private javax.swing.JLabel subtotal;
    private javax.swing.JTable tbl_supp;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel tid;
    private javax.swing.JLabel tjam;
    private javax.swing.JTextField tno;
    private javax.swing.JLabel tpos;
    // End of variables declaration//GEN-END:variables
}
